eureka:
  client:
    enabled: false
    fetch-registry: true
    register-with-eureka: false
spring:
  datasource:
      driverClassName: com.mysql.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/deepexi_user?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
  h2:
    console:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
swagger:
  base-package: org.hehaoming.user.controller
  info:
    version: "1.0.0"
    title: "Swagger Petstore"
    contact:
      email: "apiteam@swagger.io"
