swagger:
  enabled: false
server:
  error:
    include-stacktrace: never
    include-exception: false
management:
  endpoints:
    web:
      exposure:
        include: 'health, info'
spring:
  datasource:
    username: root
    password: root
    url: 'jdbc:mysql://127.0.0.1:3306/db_name'
