spring:
  application:
    name: user-service
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
server:
  error:
    include-stacktrace: always
    include-exception: true
logging:
  file: 'logs/${spring.application.name}.log'
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: '*'
mybatis:
  mapper-locations: 'classpath:mapper/*.xml'
