spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: root
    url: 'jdbc:h2:mem:test'
  h2:
    console:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
