spring:
  application:
    name: message-service
  profiles:
    active: local
#swagger:
#  base-package: org.hehaoming.user.controller
#  info:
#    title: message-service
server:
  error:
    include-stacktrace: always
    include-exception: true
logging:
  file: 'logs/${spring.application.name}.log'
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: '*'
mybatis:
  mapper-locations: 'classpath:mapper/*.xml'
  config-location: 'classpath:mybatis-config.xml'